### ISSUE TITLE
Custom Nodes are not re-installed after restarting of projects

### ISSUE THREAD

**Issue by sammachin** [FlowFuse/nr-launcher#24]
### Current Behavior

When projects are restarted after an outage any custom nodes that were installed are not re-installed

### Expected Behavior

All the nodes that were previously installed should be re-installed.

### Environment

FlowForge version: 0.2.0
• Node.js version: 16.x
• npm version: 8.x
• Platform/OS: Mac
• Browser: Chrome

**Comment by sammachin** [comment]
`externalModules.autoInstall` is already set to `true`
https://github.com/flowforge/flowforge-nr-launcher/blob/db6ffa925caedd21d855bfdefcdc4ece4dcdf96e/lib/runtimeSettings.js#L112

**Comment by knolleary** [comment]
That was added this week for 0.3... so in theory, aside from testing, no further work is needed.

**Comment by hardillb** [comment]
I've tested this using the localfs driver with the following steps
- create project
- log in to project
- use pallet manager to install node-red-node-base64
- stop the project
- cd flowforge/var/projects/<id>/node_modules
- rm -rf node-red-node-base64
- restart the project

Logs say node is reinstalled and it's present in the node_modules dirctory in the userDir.

I can probably manage to do the same in staging if you want, but I'm happy this is fixed because all the code paths should be the same for the container based drivers

**Comment by sammachin** [comment]
Given that:

We understand what the cause of the big was, node-red setting autoInstall wasn't set. 
There isn't new code just config and it's an well understood Node-RED setting.
We've fixed that setting
Its been tested on localFS

I'm happy to call this fixed
